CREATE TABLE IF NOT EXISTS `sample` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    `name` varchar(64) NOT NULL COMMENT "名称",
    `dbdtime` DATETIME(3) DEFAULT NULL COMMENT '删除时间(程序用)',
    `dbctime` DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    `dbutime` DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE `uniq_name` (`name`)
)ENGINE=INNODB DEFAULT CHARSET = utf8mb4 COMMENT '示例表';